### PR TITLE
Update country_state_select.js.erb

### PR DESCRIPTION
**Pull request by Faisal-nfl**
Seems city-state gem upon which its dependent is sending data as
data -> cscs -> array

### CODE REVIEW

**Comment by aldefouw** [comment]
Can you elaborate on what this change is? 

Is a bug in my code or a change to the library that we're linking to?

**Comment by Faisal-nfl** [comment]
seems, that library changed its response format, so its a bug now
find_states call returns data like
date = {"cscs":[["AZ","Abu Dhabi"],["DU","Dubai"],["FU","Al Fujayrah"],["RK","Ra's al Khaymah"],["SH","Ash Shariqah"]]}

but you are looping on data insetad of data.cscs, so its not loading in states dropdown on change of country.

**Comment by aldefouw** [comment]
What version of the city-state gem are you using? 

I think a more appropriate fix would be to pin the version of the city-state gem in the gemspec file.

Otherwise people who have old versions of this fork are going to download the update without updating the dependency and experience the same problem you were ...

**Comment by Faisal-nfl** [comment]
country-state-select  "~> 3.1"
city-state (0.0.13)
I have no idea about gemspec , can you make that fix?

another thing,I know that its not a place to ask, but I really need to know that how to use multiple country, select dropdowns on page, can you guide me.

**Comment by aldefouw** [comment]
Without knowing more specifics, I can't say ... but perhaps this will give you some insight into how you might do it? 

```

var country1 = CountryStateSelect({
    country_id: "country_field1_id",
    state_id: "state_field1_id"
  });

var country2 = CountryStateSelect({
    country_id: "country_field2_id",
    state_id: "state_field2_id"
  });

```

There should not be any limit on how many times you can instantiate it.

**Comment by Faisal-nfl** [comment]
@aldefouw 
I had to fork this to make few changes.
Everything was works fine on my local machine, 
But when I deployed to live server, its giving error 
Permission denied @ rb_sysopen - /var/deploy/kids/web_head/shared/bundle/ruby/2.3.0/gems/city-state-0.0.13/lib/db/states.us

any idea about it?

**Pull request merged**
